# Welcome to Jekyll!
#

title: Hope Church Website
description: >- # this means to ignore newlines until "baseurl:"
  Pursuing God, Serving People
baseurl: "" # the subpath of your site, e.g. /blog
url: "https//www.hope-church.org.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: HopeChurchWorc